# npm i -D @typescript-eslint/eslint-plugin @typescript-eslint/parser eslint eslint-config-prettier eslint-plugin-import eslint-plugin-jsdoc eslint-plugin-node

env:
  node: true

extends:
  - prettier

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 2020
  sourceType: module
  extraFileExtensions:
    - .mjs
    - .mts

plugins:
  - "@typescript-eslint"
  - import
  - jsdoc
