sudo: false

language: node_js

matrix:
  include:
    - node_js: "10"
      env: NPM_RUN_SCRIPT=test NPM_AUDIT=true MOCHA_ARGS="-- --node-arg=--pending-deprecation --node-arg=--throw-deprecation"
    - node_js: "9"
    - node_js: "8"
    - node_js: "7"
    - node_js: "6"

install:
  - npm install
  - if [ "$NPM_AUDIT" = true ]; then npm audit; fi

script:
  - echo "--reporter dot --color" > test/mocha.opts
  - npm run build
  - npm run ${NPM_RUN_SCRIPT:-test:api} -- ${MOCHA_ARGS}
